### ISSUE TITLE
Not showing the slider button

### ISSUE THREAD

**Issue by danpalmieri** [yepsua/filament-range-field#1] opened 2022-06-26 15:39 UTC
Only the bar.

Browser: Chrome on Mac.

**Comment by oyepez003** [comment] 2022-06-27 18:48
I'm not able to reproduce the issue at the moment. I use Linux and it works in Firefox and Chrome correctly.

Thanks again @danpalmieri .

**Comment by nea** [comment] 2022-06-28 08:56
Ahoy

I am having the same issue:
![image](https://user-images.githubusercontent.com/392035/176137633-95318499-7883-4e4b-a378-11ddaf469494.png)

If I add steps, I can see where I am. But no slider itself. No console.log errors or anything, and whatever I click on the bar is correctly set just not visible. I started pretty fresh with a new filament project.

Chrome Version 103.0.5060.53, Windows 10
Filament 2.13.12


Thanks a lot

**Comment by alexmartinfr** [comment] 2022-06-28 10:16
I've the exact same issue with the following browsers on macOS 12.4:
- Chrome 103.0.5060.53
- Safari 15.5

Works on Firefox 101.0.1, almost, with a graphical glitch though:

<img width="238" alt="Capture d’écran 2022-06-28 à 12 15 42" src="https://user-images.githubusercontent.com/19224681/176155190-1a70595f-8d3f-4511-9521-45fe33dab75f.png">

**Comment by oyepez003** [comment] 2022-06-28 14:36
Ok guys, let me check how can I fix the error in Mac. Thanks for your review.

**Comment by oddvalue** [comment] 2022-10-05 11:06
Same issue here. On latest version of Laravel, Filament, and this package. Chrome on Linux (Pop!_OS 22.04 LTS).
Any progress on fixing it?

**Comment by Quadrubo** [comment] 2022-11-10 15:11
Same issue here, Brave on Linux, Firefox works but only displays the outline and not the fill.

**Comment by oyepez003** [comment] 2022-11-10 18:00
It works on Linux: Brave, Firefox, and Chrome (all the latest versions).

Brave:
![imagen](https://user-images.githubusercontent.com/1541517/201170933-f9f9977b-bceb-4a14-9166-036749a6327a.png)

Firefox:
![imagen](https://user-images.githubusercontent.com/1541517/201171336-92b90387-d1b9-4914-8111-bfc5e0811d75.png)

Chrome:
![imagen](https://user-images.githubusercontent.com/1541517/201171688-d551ab88-9adb-4ffe-a234-3661ca03f8cf.png)

Not able to replicate in IOs yet.

**Comment by oddvalue** [comment] 2022-11-10 23:40
@oyepez003 Am I missing something? Your screenshots don't actually show any range fields. It's just toggles and selects :thinking:

**Comment by oyepez003** [comment] 2022-11-11 17:04
Sorry guys, you are right @oddvalue, next the screenshots:

**Firefox:**
![imagen](https://user-images.githubusercontent.com/1541517/201391213-801268a7-081b-4c60-ac3d-dbb7131c8ca1.png)

**Brave:**
![imagen](https://user-images.githubusercontent.com/1541517/201391441-dd088361-b9c4-4b2e-8cb4-13b518868769.png)

**Chrome:**
![imagen](https://user-images.githubusercontent.com/1541517/201391626-24c5ff5a-03cf-41b5-a3b0-c5c914d75bf0.png)

**Comment by bumbummen99** [comment] 2022-11-12 18:07
@oyepez003 My filament app.css is not including all the tailwind classes you used in the component, your package does also not provide them. This might be simply an incompatibility between Filament CSS build and this package instead of the actual logic.
I am using filament version v2.16.46

**v2.16.46 app.css**
https://github.com/filamentphp/filament/blob/v2.16.46/packages/admin/dist/app.css
Try to search for `.focus\:bg-primary-200`

**Comment by habib19** [comment] 2023-01-03 09:48
I've the exact same issue with chrome browser.

**Comment by frode81** [comment] 2023-02-19 13:02
Any update regarding this? I have the same issue.

**Comment by studiowizjo** [comment] 2023-04-20 17:30
Same here. If you get rid of all classes from input, it displays default for browser, so point marking current value displays correctly. Hovewer it is not possible to move it: both clicking on range or on defined steps below. Steps are marking as selected, but range value indicator is not moving.

**Comment by elegisandi** [comment] 2023-06-13 07:05
same here, ive found a way to show the slider thumb via the plugin CSS.
just comment out the 2 lines below.

```
.filament-forms-range-component::-webkit-slider-thumb {
    /* -webkit-appearance: none; */
    /* appearance: none; */
   ....
}
```

NOTE: just make sure to publish the assets `php artisan vendor:publish --tag="filament-range-field-assets"`

**Comment by oddvalue** [comment] 2023-06-14 11:39
Further to @elegisandi's comment; This issue is caused by the fact that the css uses custom properties that are not present in a default Filament install. e.g. `var(--color-primary-600)`

Presumably @oyepez003 is using the package in an app with a custom stylesheet. 

My workaround has been to make my own stylesheet based on this https://github.com/yepsua/filament-range-field/blob/master/resources/css/filament-forms-range-component.css that actually works.

**Comment by naumantoor** [comment] 2023-07-27 12:59
any one found this the fix for this issue ?

**Comment by danpalmieri** [comment] 2023-10-04 17:09
@oddvalue is right.
My fork is working with filament v3 and a hard coded color.

[https://github.com/danpalmieri/filament-range-field](https://github.com/danpalmieri/filament-range-field)

@oyepez003 can I make a PR?

**Comment by oyepez003** [comment] 2023-12-29 06:10
Fixed by using the latest release: https://github.com/yepsua/filament-range-field/releases/tag/v0.3.4

**Closed as completed by oyepez003** 2023-12-29 06:10 UTC

**Comment by elegisandi** [comment] 2024-01-09 14:25
for those still using filamentphp v2. add the ff lines at the top of the plugin's custom CSS file.

```
@layer base {
    :root {
        --color-primary-600: replace-with-your-own-color;
        --color-primary-400: replace-with-your-own-color;
        --color-primary-300: replace-with-your-own-color;
        /* ... */
    }
}
```
see https://tailwindcss.com/docs/customizing-colors#using-css-variables for reference.
